name: Run Agents Script

on:
  schedule:
    - cron: '*/30 * * * *'   # كل 30 دقيقة
  workflow_dispatch:          # يسمح بالتشغيل اليدوي أيضًا

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run main script
      env:
        # هنا تضيف أي متغيرات سرية مثل API keys أو بيانات الدخول
        REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
        REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
        REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
        REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
        PINTEREST_TOKEN: ${{ secrets.PINTEREST_TOKEN }}
      run: python main.py
